name: Squad APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Init Buildozer
      run: buildozer init || echo "Already initialized"

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Squad-APK
        path: bin/*.apk
